Install a not successful cross-compile anyway and see what we get. inform the builder if things went wrong.

diff --git a/icu4c/source/rjdMake b/icu4c/source/rjdMake
--- a/icu4c/source/rjdMake
+++ b/icu4c/source/rjdMake
@@ -16,9 +16,9 @@ mkdir buildLinux
 mkdir buildAmiga
 
 pushd buildLinux
-../runConfigureICU Linux/gcc || { echo "Error during configure" ; exit 1 ; }
+../runConfigureICU Linux/gcc || { echo "Error during BUILD-MACHINE configure" ; exit 1 ; }
 CROSS_BUILD_FULL_PATH="$(pwd)"
-make -j "$CORES" || { echo "Error during building" ; exit 1 ; }
+make -j "$CORES" || { echo "Error during BUILD-MACHINE building" ; exit 1 ; }
 popd
 
 pushd buildAmiga
@@ -43,15 +43,25 @@ fi
     CPPFLAGS="-mcrt=clib2" \
     CXXFLAGS="-mcrt=clib2" \
     CFLAGS="-mcrt=clib2" \
+    LDFLAGS="-mcrt=clib2 -athread=native" \
     --disable-tests --disable-samples --disable-shared --enable-static --disable-dyload --enable-release --disable-extras \
     --disable-debug \
     --host=ppc-amigaos \
     --with-cross-build="$CROSS_BUILD_FULL_PATH" \
     --prefix=$INSTALL_PREFIX || \
-    	{ echo "Error during configure for cross" ; exit 1 ; }
-THREADSCXXFLAGS=-athread=native make -j $CORES || { echo "Error during building for cross" ; exit 1 ; }
+    	{ echo "Error during CROSS-MACHINE configure" ; exit 1 ; }
+SUCC="successful"
+THREADSCXXFLAGS=-athread=native make -j $CORES
+if (( ${?} ))
+then
+    SUCC="not fully successful, but as much as possible was installed to $INSTALL_PREFIX"
+fi
 make install
 popd
 
-echo "Finished. See inside \"$INSTALL_PREFIX\""
+echo "###########################################################################"
+echo "###########################################################################"
+echo "Finished. See inside \"$INSTALL_PREFIX\". CROSS-MACHINE building was $SUCC."
+echo "###########################################################################"
+echo "###########################################################################"
 exit 0
